# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Documents\GitHub\FitnessGUI\ohje.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(351, 122)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 321, 51))
        self.label.setObjectName("label")
        self.closePushButton = QtWidgets.QPushButton(Dialog)
        self.closePushButton.setGeometry(QtCore.QRect(130, 70, 91, 21))
        self.closePushButton.setObjectName("closePushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tämä on ohje, jossa kerrotaan, miten tätä ohjelmaa käytetään"))
        self.closePushButton.setText(_translate("Dialog", "Sulje"))
