# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pc\Documents\GitHub\FitnessGUI\removeUserDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.userComboBox = QtWidgets.QComboBox(Dialog)
        self.userComboBox.setGeometry(QtCore.QRect(10, 50, 201, 22))
        self.userComboBox.setObjectName("userComboBox")
        self.userLabel = QtWidgets.QLabel(Dialog)
        self.userLabel.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.userLabel.setObjectName("userLabel")
        self.removePushButton = QtWidgets.QPushButton(Dialog)
        self.removePushButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.removePushButton.setObjectName("removePushButton")
        self.closePushButton_2 = QtWidgets.QPushButton(Dialog)
        self.closePushButton_2.setGeometry(QtCore.QRect(110, 100, 75, 23))
        self.closePushButton_2.setObjectName("closePushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.userLabel.setText(_translate("Dialog", "Käyttäjä"))
        self.removePushButton.setText(_translate("Dialog", "Poista"))
        self.closePushButton_2.setText(_translate("Dialog", "Sulje"))
